apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: client:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER1_HOST
              value: "server1-service"
            - name: SERVER1_PORT
              value: "9999"
            - name: SERVER2_HOST
              value: "server2-service"
            - name: SERVER2_PORT
              value: "10000"
            - name: MESSAGE_STATE_FILE
              value: "/data/message-state.txt" # Path to state file
          command: ["node", "client.js"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
