apiVersion: v1
kind: Service
metadata:
  name: server1-service
spec:
  selector:
    app: server1
  ports:
    - protocol: TCP
      port: 9999       # Exposed port for the client
      targetPort: 9999 # Port used by the server1 container
  type: ClusterIP
