apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: server1
  template:
    metadata: 
      labels:
        app: server1
    spec:
      containers:
        - name: server1
          image: server1:latest
          imagePullPolicy: IfNotPresent 
          ports: 
            - containerPort: 9999
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc